- hosts: Docker_Servers
  become: true
  tasks:
  - name: Login to Dockerhub
    command: docker login -u devdapo -p @Nigeria95

  - name: Stop any running container
    command: docker stop pet-adoption-container
    ignore_errors: yes

  - name: Remove Stopped Container
    command: docker rm pet-adoption-container
    ignore_errors: yes
  
  - name: Remove Docker Image
    command: docker rmi devdapo/pet-adoption-image
    ignore_errors: yes

  - name: Pull docker Image from docker Hub
    command: docker pull devdapo/pet-adoption-image
    ignore_errors: yes
  
  - name: Create Container from image
    command: docker run -it -d --name pet-adoption-container -p 8080:8085 --restart unless-stopped devdapo/pet-adoption-image
    ignore_errors: yes